/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BalancePinRouteImport } from './routes/balance-pin'
import { Route as BalanceSuccessRouteImport } from './routes/balance-success'
import { Route as CheckBalanceRouteImport } from './routes/check-balance'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PinRouteImport } from './routes/pin'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SuccessDetailsRouteImport } from './routes/success-details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancePinRoute = BalancePinRouteImport.update({
  id: '/balance-pin',
  path: '/balance-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceSuccessRoute = BalanceSuccessRouteImport.update({
  id: '/balance-success',
  path: '/balance-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckBalanceRoute = CheckBalanceRouteImport.update({
  id: '/check-balance',
  path: '/check-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessDetailsRoute = SuccessDetailsRouteImport.update({
  id: '/success-details',
  path: '/success-details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance-pin': typeof BalancePinRoute
  '/balance-success': typeof BalanceSuccessRoute
  '/check-balance': typeof CheckBalanceRoute
  '/pay': typeof PayRoute
  '/pin': typeof PinRoute
  '/scan': typeof ScanRoute
  '/success': typeof SuccessRoute
  '/success-details': typeof SuccessDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance-pin': typeof BalancePinRoute
  '/balance-success': typeof BalanceSuccessRoute
  '/check-balance': typeof CheckBalanceRoute
  '/pay': typeof PayRoute
  '/pin': typeof PinRoute
  '/scan': typeof ScanRoute
  '/success': typeof SuccessRoute
  '/success-details': typeof SuccessDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balance-pin': typeof BalancePinRoute
  '/balance-success': typeof BalanceSuccessRoute
  '/check-balance': typeof CheckBalanceRoute
  '/pay': typeof PayRoute
  '/pin': typeof PinRoute
  '/scan': typeof ScanRoute
  '/success': typeof SuccessRoute
  '/success-details': typeof SuccessDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance-pin'
    | '/balance-success'
    | '/check-balance'
    | '/pay'
    | '/pin'
    | '/scan'
    | '/success'
    | '/success-details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance-pin'
    | '/balance-success'
    | '/check-balance'
    | '/pay'
    | '/pin'
    | '/scan'
    | '/success'
    | '/success-details'
  id:
    | '__root__'
    | '/'
    | '/balance-pin'
    | '/balance-success'
    | '/check-balance'
    | '/pay'
    | '/pin'
    | '/scan'
    | '/success'
    | '/success-details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalancePinRoute: typeof BalancePinRoute
  BalanceSuccessRoute: typeof BalanceSuccessRoute
  CheckBalanceRoute: typeof CheckBalanceRoute
  PayRoute: typeof PayRoute
  PinRoute: typeof PinRoute
  ScanRoute: typeof ScanRoute
  SuccessRoute: typeof SuccessRoute
  SuccessDetailsRoute: typeof SuccessDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance-pin': {
      id: '/balance-pin'
      path: '/balance-pin'
      fullPath: '/balance-pin'
      preLoaderRoute: typeof BalancePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance-success': {
      id: '/balance-success'
      path: '/balance-success'
      fullPath: '/balance-success'
      preLoaderRoute: typeof BalanceSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-balance': {
      id: '/check-balance'
      path: '/check-balance'
      fullPath: '/check-balance'
      preLoaderRoute: typeof CheckBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-details': {
      id: '/success-details'
      path: '/success-details'
      fullPath: '/success-details'
      preLoaderRoute: typeof SuccessDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalancePinRoute: BalancePinRoute,
  BalanceSuccessRoute: BalanceSuccessRoute,
  CheckBalanceRoute: CheckBalanceRoute,
  PayRoute: PayRoute,
  PinRoute: PinRoute,
  ScanRoute: ScanRoute,
  SuccessRoute: SuccessRoute,
  SuccessDetailsRoute: SuccessDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
